// Pure Dart — no Flutter imports
import 'enums.dart';

class GovernmentDef {
  final GovernmentType type;
  final int illegalReaction; // 0=lenient..5=arrest on sight for illegal goods
  final int policeStrength;  // 0-7
  final int pirateStrength;  // 0-7
  final int traderStrength;  // 0-7
  final int minTechLevel;
  final int maxTechLevel;
  final int bribeLevel;      // 0=never, higher = more bribable
  final bool drugsOK;        // narcotics legal
  final bool firearmsOK;     // firearms legal
  final TradeGood? wantedGood; // good wanted (scarce) in this government

  const GovernmentDef({
    required this.type,
    required this.illegalReaction,
    required this.policeStrength,
    required this.pirateStrength,
    required this.traderStrength,
    required this.minTechLevel,
    required this.maxTechLevel,
    required this.bribeLevel,
    required this.drugsOK,
    required this.firearmsOK,
    this.wantedGood,
  });

  String get displayName => type.displayName;

  /// All 17 government types as defined in the original Space Trader.
  static const List<GovernmentDef> all = [
    GovernmentDef(
      type: GovernmentType.anarchy,
      illegalReaction: 0,
      policeStrength: 0,
      pirateStrength: 7,
      traderStrength: 2,
      minTechLevel: 0,
      maxTechLevel: 5,
      bribeLevel: 5,
      drugsOK: true,
      firearmsOK: true,
      wantedGood: TradeGood.robots,
    ),
    GovernmentDef(
      type: GovernmentType.capitalistState,
      illegalReaction: 3,
      policeStrength: 3,
      pirateStrength: 3,
      traderStrength: 7,
      minTechLevel: 1,
      maxTechLevel: 7,
      bribeLevel: 3,
      drugsOK: false,
      firearmsOK: true,
      wantedGood: TradeGood.narcotics,
    ),
    GovernmentDef(
      type: GovernmentType.communistState,
      illegalReaction: 5,
      policeStrength: 7,
      pirateStrength: 1,
      traderStrength: 4,
      minTechLevel: 1,
      maxTechLevel: 6,
      bribeLevel: 0,
      drugsOK: false,
      firearmsOK: false,
      wantedGood: TradeGood.games,
    ),
    GovernmentDef(
      type: GovernmentType.confederacy,
      illegalReaction: 3,
      policeStrength: 4,
      pirateStrength: 4,
      traderStrength: 5,
      minTechLevel: 1,
      maxTechLevel: 7,
      bribeLevel: 2,
      drugsOK: false,
      firearmsOK: true,
      wantedGood: TradeGood.machines,
    ),
    GovernmentDef(
      type: GovernmentType.corporateState,
      illegalReaction: 4,
      policeStrength: 5,
      pirateStrength: 2,
      traderStrength: 7,
      minTechLevel: 2,
      maxTechLevel: 7,
      bribeLevel: 3,
      drugsOK: false,
      firearmsOK: true,
      wantedGood: TradeGood.ore,
    ),
    GovernmentDef(
      type: GovernmentType.cyberneticState,
      illegalReaction: 5,
      policeStrength: 7,
      pirateStrength: 2,
      traderStrength: 6,
      minTechLevel: 5,
      maxTechLevel: 7,
      bribeLevel: 0,
      drugsOK: false,
      firearmsOK: false,
      wantedGood: TradeGood.robots,
    ),
    GovernmentDef(
      type: GovernmentType.democracy,
      illegalReaction: 4,
      policeStrength: 4,
      pirateStrength: 2,
      traderStrength: 6,
      minTechLevel: 2,
      maxTechLevel: 7,
      bribeLevel: 1,
      drugsOK: false,
      firearmsOK: false,
      wantedGood: null,
    ),
    GovernmentDef(
      type: GovernmentType.dictatorship,
      illegalReaction: 3,
      policeStrength: 5,
      pirateStrength: 4,
      traderStrength: 3,
      minTechLevel: 0,
      maxTechLevel: 6,
      bribeLevel: 4,
      drugsOK: false,
      firearmsOK: false,
      wantedGood: TradeGood.food,
    ),
    GovernmentDef(
      type: GovernmentType.fascistState,
      illegalReaction: 5,
      policeStrength: 7,
      pirateStrength: 3,
      traderStrength: 3,
      minTechLevel: 1,
      maxTechLevel: 6,
      bribeLevel: 0,
      drugsOK: false,
      firearmsOK: false,
      wantedGood: TradeGood.firearms,
    ),
    GovernmentDef(
      type: GovernmentType.feudalState,
      illegalReaction: 1,
      policeStrength: 1,
      pirateStrength: 6,
      traderStrength: 2,
      minTechLevel: 0,
      maxTechLevel: 4,
      bribeLevel: 4,
      drugsOK: true,
      firearmsOK: true,
      wantedGood: TradeGood.furs,
    ),
    GovernmentDef(
      type: GovernmentType.militaryState,
      illegalReaction: 5,
      policeStrength: 7,
      pirateStrength: 2,
      traderStrength: 4,
      minTechLevel: 2,
      maxTechLevel: 7,
      bribeLevel: 0,
      drugsOK: false,
      firearmsOK: true,
      wantedGood: TradeGood.machines,
    ),
    GovernmentDef(
      type: GovernmentType.monarchy,
      illegalReaction: 3,
      policeStrength: 4,
      pirateStrength: 3,
      traderStrength: 4,
      minTechLevel: 1,
      maxTechLevel: 6,
      bribeLevel: 3,
      drugsOK: false,
      firearmsOK: true,
      wantedGood: TradeGood.ore,
    ),
    GovernmentDef(
      type: GovernmentType.pacifistState,
      illegalReaction: 4,
      policeStrength: 3,
      pirateStrength: 1,
      traderStrength: 6,
      minTechLevel: 1,
      maxTechLevel: 7,
      bribeLevel: 1,
      drugsOK: false,
      firearmsOK: false,
      wantedGood: null,
    ),
    GovernmentDef(
      type: GovernmentType.socialistState,
      illegalReaction: 3,
      policeStrength: 4,
      pirateStrength: 2,
      traderStrength: 5,
      minTechLevel: 1,
      maxTechLevel: 5,
      bribeLevel: 2,
      drugsOK: false,
      firearmsOK: false,
      wantedGood: TradeGood.medicine,
    ),
    GovernmentDef(
      type: GovernmentType.stateOfSatori,
      illegalReaction: 2,
      policeStrength: 1,
      pirateStrength: 1,
      traderStrength: 3,
      minTechLevel: 1,
      maxTechLevel: 5,
      bribeLevel: 3,
      drugsOK: true,
      firearmsOK: false,
      wantedGood: TradeGood.narcotics,
    ),
    GovernmentDef(
      type: GovernmentType.technocracy,
      illegalReaction: 4,
      policeStrength: 5,
      pirateStrength: 2,
      traderStrength: 5,
      minTechLevel: 4,
      maxTechLevel: 7,
      bribeLevel: 1,
      drugsOK: false,
      firearmsOK: false,
      wantedGood: TradeGood.robots,
    ),
    GovernmentDef(
      type: GovernmentType.theocracy,
      illegalReaction: 5,
      policeStrength: 5,
      pirateStrength: 2,
      traderStrength: 4,
      minTechLevel: 0,
      maxTechLevel: 5,
      bribeLevel: 1,
      drugsOK: false,
      firearmsOK: false,
      wantedGood: TradeGood.narcotics,
    ),
  ];

  static GovernmentDef forType(GovernmentType type) {
    return all.firstWhere((d) => d.type == type);
  }
}
